print('What happened with all the files of mine?')
print("Did they vanish into thin air?")
print("And what happened to the RGB colours?")
print("And what is this thing which doesn't move away when I type?")
print("Whatever, let's do some proggraming")
a=int(input("Enter 1st number :"))
b=int(input("Enter 2nd number :"))
c=a*b
print(c)
print(type(c))