CREATE DATABASE shop;
USE shop;

CREATE TABLE PRODUCTS (
	PRODUCT_ID VARCHAR(50),
	PRODUCT_NAME VARCHAR(50),
	SUPPLIER_ID VARCHAR(50), 
	CATEGORY_ID VARCHAR(50),
	UNIT VARCHAR(50),
	PRICE REAL 
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
('1', 'CHAIS', '1', '1', '10 BOXES*20 BAGS', 18),
('2', 'CHANG', '1', '1', '24-12 OZ BOTTLES', 19),
('3', 'ANISEED SYRUP', '1', '2', '12-550 ML BOTTLES', 10),
('4', 'CHEF ANTON SEASONING', '2', '2', '48- 6 OZ JARS', 22),
('5', 'CHEF ANTON MIX', '2', '2', '36 BOXES', 21.35);

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS;

SELECT SUM(PRICE) AS Average_Sum
FROM PRODUCTS;

