from tkinter import *
root = Tk()
root.geometry("400x300")
root.title("main")
top = Toplevel()
top.geometry("100x100")
top.title("toplevel")
l2 = Label(top, text="This is a Toplevel window")
l2.pack()
top.mainloop()
l = Label(root, text="This is the root window")
btn = Button(root, text="Click her to open another window", command= topwin)
l.pack()
btn.pack()